---
- hosts: nodo
  vars:
    mynetworks: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 192.168.1.240/32 192.168.1.179/32 8.8.4.4/32'
    paquetes:
      - apache2
      - dovecot-imapd
      - postfix
  tasks:
  - name: Instalacion de paquete
    apt:
      name: '{{ paquetes }}'
      state: present
  - name: Escribir configuracion de postfix
    template:
      src: postfix-main.cf.j2
      dest: /etc/postfix/main.cf
    notify: 
    - name: reinicio postfix


  handlers:
    - name: reloaded dovecot
      service:
        name: dovecot
        state: reloaded
        enabled: yes
    - name: reloaded apache2
      service:
        name: apache2
        state: reloaded
        enabled: yes
    - name: reinicio postfix
      service:
        name: postfix
        state: restarted
        enabled: yes

